trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job!
- stage: DevDeploy
  dependsOn: build
  jobs:
  - job: SecondJob
    steps:
    - bash: echo Deploy Second Job!
- stage: QADeploy
  dependsOn: build
  jobs:
  - job: ThirdJob
    steps:
    - bash: echo QA Third Job!
- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: FourthJob
    steps:
    - bash: echo Prod Fourth Job!