trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job!
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactsStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'


# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: build
#   jobs:
#   - job: SecondJob
#     steps:
#     - bash: echo $(environment) Deploy Second Job!
# - stage: QADeploy
#   variables:
#     environment: QA
#   dependsOn: build
#   jobs:
#   - job: ThirdJob
#     steps:
#     - bash: echo $(environment) Third Job!
# - stage: ProdDeploy
#   variables:
#     environment: Prod
#   dependsOn: 
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: FourthJob
#     steps:
#     - bash: echo $(environment) Fourth Job!