trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job!
    - bash: echo $(PipelineLevelVariable)
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: build
  jobs:
  - job: SecondJob
    steps:
    - bash: echo $(environment) Deploy Second Job!
- stage: QADeploy
  variables:
    environment: QA
  dependsOn: build
  jobs:
  - job: ThirdJob
    steps:
    - bash: echo $(environment) Third Job!
- stage: ProdDeploy
  variables:
    environment: Prod
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: FourthJob
    steps:
    - bash: echo $(environment) Fourth Job!